package tz.go.moh.him.ffars.mediator.e9.domain;

import com.google.gson.annotations.SerializedName;
import tz.go.moh.him.mediator.core.exceptions.ArgumentNullException;
import tz.go.moh.him.mediator.core.utils.StringUtils;

import java.util.List;

public class Expenditure {
    /**
     * An id generated by MSD Epicor to uniquely identify the payload being passed between the two systems
     */
    @SerializedName("UID")
    private String uid;

    /**
     * Actual Transaction date
     */
    @SerializedName("ApplyDate")
    private String applyDate;

    @SerializedName("Items")
    private List<Item> items;

    public Expenditure(String uid, String applyDate, List<Item> items) {
        if (StringUtils.isNullOrEmpty(uid)) {
            throw new ArgumentNullException("uuid - Value cannot be null");
        }

        if (StringUtils.isNullOrEmpty(applyDate)) {
            throw new ArgumentNullException("Apply Date - Value cannot be null");
        }

        if (items == null || items.isEmpty()) {
            throw new ArgumentNullException("Items - Value cannot be null");
        }

        this.uid = uid;
        this.applyDate = applyDate;
        this.items = items;
    }

    public String getUid() {
        return uid;
    }

    public String getApplyDate() {
        return applyDate;
    }

    public List<Item> getItems() {
        return items;
    }

    public static class Item {
        /**
         * Date generated in MSD Epicor by sales officer
         */
        @SerializedName("OrderDate")
        private String orderDate;

        /**
         * Unique Invoice Number
         */
        @SerializedName("InvoiceNumber")
        private String invoiceNumber;

        /**
         * A MSD code that identifies the Health Facility possessing the data in the payload
         */
        @SerializedName("FacilityCode")
        private String facilityCode;

        /**
         * Name of the health facility
         */
        @SerializedName("FacilityName")
        private String facilityName;

        /**
         * Indicates whether the facility is a Dispensaries, Health Centers or council Hospitals
         */
        @SerializedName("FacilityType")
        private String facilityType;

        /**
         * Indicates facility status either active/not
         */
        @SerializedName("Operational")
        private boolean operational;

        /**
         * Specify Invoice total (InKind + other source)
         */
        @SerializedName("TotalCost")
        private double totalCost;

        /**
         * Central government fund source via MSD
         */
        @SerializedName("InKInd")
        private double inKInd;

        /**
         * Any other facility fund source
         */
        @SerializedName("OtherSource")
        private double otherSource;

        @SerializedName("Description")
        private String description;

        /**
         * Current balance remain for the facility
         */
        @SerializedName("CurrentBalance")
        private double CurrentBalance;

        public Item(String orderDate, String invoiceNumber, String facilityCode, String facilityName, String facilityType, boolean operational, double totalCost, double inKInd, double otherSource, String description, double currentBalance) {
            if (StringUtils.isNullOrEmpty(orderDate)) {
                throw new ArgumentNullException("Order Date - Value cannot be null");
            }

            if (StringUtils.isNullOrEmpty(invoiceNumber)) {
                throw new ArgumentNullException("Invoice Number - Value cannot be null");
            }

            if (StringUtils.isNullOrEmpty(facilityCode)) {
                throw new ArgumentNullException("Facility Code - Value cannot be null");
            }

            if (StringUtils.isNullOrEmpty(facilityName)) {
                throw new ArgumentNullException("Facility Name - Value cannot be null");
            }

            if (StringUtils.isNullOrEmpty(facilityType)) {
                throw new ArgumentNullException("Facility Type - Value cannot be null");
            }

            this.orderDate = orderDate;
            this.invoiceNumber = invoiceNumber;
            this.facilityCode = facilityCode;
            this.facilityName = facilityName;
            this.facilityType = facilityType;
            this.operational = operational;
            this.totalCost = totalCost;
            this.inKInd = inKInd;
            this.otherSource = otherSource;
            this.description = description;
            CurrentBalance = currentBalance;
        }

        public String getOrderDate() {
            return orderDate;
        }

        public String getInvoiceNumber() {
            return invoiceNumber;
        }

        public String getFacilityCode() {
            return facilityCode;
        }

        public String getFacilityName() {
            return facilityName;
        }

        public String getFacilityType() {
            return facilityType;
        }

        public boolean isOperational() {
            return operational;
        }

        public double getTotalCost() {
            return totalCost;
        }

        public double getInKInd() {
            return inKInd;
        }

        public double getOtherSource() {
            return otherSource;
        }

        public String getDescription() {
            return description;
        }

        public double getCurrentBalance() {
            return CurrentBalance;
        }
    }
}
